language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_18857f0d2e78_key -iv $encrypted_18857f0d2e78_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'vanjor'
- git config --global user.email vanjor2008@gmail.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-deployer-git --save
script:
- hexo deploy
cache:
  directories:
  - node_modules

